Repository codeit-sprint-fullstack/7-sprint-mission-fe, pull requests merged in 2025-04, with the labels that each got.

#8 [김태홍] sprint 1,2
  README.md
  faq.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/panda_logo.png
  image/word_logo.png
  index.html
  items.html
  login/image/close eye.png
  login/image/google.png
  login/image/img_panda.png
  login/image/kakao.png
  login/image/logo.png
  login/image/open eye.png
  login/login.html
  login/signup.html
  login/stlyeSheet/signup.css
  login/stlyeSheet/style.css
  privacy.html
  styleSheet/reset.css
  styleSheet/style.css
Labels: 매운맛🔥

#6 [정부광] Sprint1, 2
  pandaMarket/images/home/end-img.png
  pandaMarket/images/home/facebook.svg
  pandaMarket/images/home/hot-img.png
  pandaMarket/images/home/instagram.svg
  pandaMarket/images/home/panda-face.svg
  pandaMarket/images/home/panda-full.png
  pandaMarket/images/home/search-img.png
  pandaMarket/images/home/sell-img.png
  pandaMarket/images/home/twitter.svg
  pandaMarket/images/home/youtube.svg
  pandaMarket/images/login/google.svg
  pandaMarket/images/login/kakaoTalk-backgound.svg
  pandaMarket/images/login/kakaoTalk.svg
  pandaMarket/index.html
  pandaMarket/login.html
  pandaMarket/script/login.js
  pandaMarket/sign.html
  pandaMarket/style/login.css
  pandaMarket/style/reset.css
  pandaMarket/style/sign.css
  pandaMarket/style/style.css
Labels: 매운맛🔥, 최종 제출

#10 김성근 sprint1,2
  PretendardVariable.woff2
  imges/99FE484C5C3451F218 1.svg
  imges/Component 2-1.svg
  imges/Component 2-2.svg
  imges/Component 2.svg
  imges/Group.svg
  imges/Group2.svg
  imges/Img_home_01.svg
  imges/Img_home_02.svg
  imges/Img_home_03.svg
  imges/Img_home_bottom.svg
  imges/Img_home_top.svg
  imges/btn_visibility_on_24px.svg
  imges/google.svg
  imges/googleback.svg
  imges/ic_instagram.svg
  imges/ic_twitter.svg
  imges/kakao.svg
  imges/판다 얼굴.svg
  index.html
  login.css
  login.html
  reser.css
  signup.html
  style.css
Labels: 순한맛🐑, 최종 제출

#11 [정우진] sprint1
  assets/.DS_Store
  assets/Component_2.svg
  assets/Component_3.svg
  assets/Img_home_01.svg
  assets/Img_home_02.svg
  assets/Img_home_03.svg
  assets/Img_home_bottom.svg
  assets/Img_home_top.svg
  assets/btn_visibility_on_24px.png
  assets/ic_facebook.svg
  assets/ic_instagram.svg
  assets/ic_twitter.svg
  assets/ic_youtube.svg
  assets/panda_logo.svg
  common.js
  index.html
  login.css
  login.html
  login.js
  reset.css
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥, 최종 제출

#12 [김제성] sprint 1, 2
  미션 1 & 2/Component 2.png
  미션 1 & 2/Component 2.svg
  미션 1 & 2/Component 3.svg
  미션 1 & 2/Img_home_01.png
  미션 1 & 2/Img_home_02.png
  미션 1 & 2/Img_home_03.png
  미션 1 & 2/Img_home_bottom.png
  미션 1 & 2/Img_home_top.png
  미션 1 & 2/btn_visibility_on_24px.svg
  미션 1 & 2/ic_facebook.svg
  미션 1 & 2/ic_instagram.svg
  미션 1 & 2/ic_twitter.svg
  미션 1 & 2/ic_youtube.svg
  미션 1 & 2/index.html
  미션 1 & 2/login.css
  미션 1 & 2/login.html
  미션 1 & 2/logo for login.svg
  미션 1 & 2/reset.css
  미션 1 & 2/signin.html
  미션 1 & 2/style.css
  미션 1 & 2/판다 얼굴.png
  미션 1 & 2/판다 얼굴.svg
Labels: 순한맛🐑, 최종 제출
