Repository codeit-sprint-fullstack/7-sprint-mission-fe, pull requests merged in 2025-05, with the labels that each got.

#19 [김미정] sprint mission 1,2
  .DS_Store
  FAQ.html
  Img_home_01.svg
  Img_home_02.svg
  Img_home_03.png
  Img_home_bottom.svg
  Img_home_top.svg
  README.md
  google.png
  ic_facebook.svg
  ic_instagram.svg
  ic_twitter.svg
  ic_youtube.svg
  img_pandaface.svg
  index.html
  item.html
  kakao.png
  login.html
  privacy.html
  readme 복사본.md
  reset.css
  signup.html
  style_index.css
  style_login.css
  style_signup.css
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR, 진행 중 🏃

#33 [진주혁] Sprint 3
  sprint_mission3/faq.html
  sprint_mission3/images/home/bottom-banner-image.png
  sprint_mission3/images/home/feature1-image.png
  sprint_mission3/images/home/feature2-image.png
  sprint_mission3/images/home/feature3-image.png
  sprint_mission3/images/home/hero-image.png
  sprint_mission3/images/logo/favicon.ico
  sprint_mission3/images/logo/panda-market-logo-big.png
  sprint_mission3/images/logo/panda-market-logo.png
  sprint_mission3/images/logo/pw-eye-closed.png
  sprint_mission3/images/logo/pw-eye-open.png
  sprint_mission3/images/sns/facebook-logo.svg
  sprint_mission3/images/sns/google-logo.svg
  sprint_mission3/images/sns/instagram-logo.svg
  sprint_mission3/images/sns/kakaotalk-logo.svg
  sprint_mission3/images/sns/twitter-logo.svg
  sprint_mission3/images/sns/youtube-logo.svg
  sprint_mission3/index.html
  sprint_mission3/items.html
  sprint_mission3/login.html
  sprint_mission3/privacy.html
  sprint_mission3/readme.md
  sprint_mission3/script.js
  sprint_mission3/signup.html
  sprint_mission3/styles/global.css
  sprint_mission3/styles/home.css
  sprint_mission3/styles/login.css
  sprint_mission3/styles/reset.css
  sprint_mission3/styles/signup.css
Labels: 미완성🫠, 진행 중 🏃

#22 [정부광] sprint 3
  pandaMarket/index.html
  pandaMarket/login.html
  pandaMarket/script/login.js
  pandaMarket/script/sign.js
  pandaMarket/sign.html
  pandaMarket/style/login.css
  pandaMarket/style/sign.css
  pandaMarket/style/style.css
Labels: 매운맛🔥, 최종 제출

#26 [정남영] 스프린트미션3
  index.html
  login.html
  login.js
  loginstyle.css
  signup.html
  signup.js
  userData.js
Labels: 순한맛🐑, 최종 제출

#29 [오해상] sprint3
  btn_visibility_see.png
  form-login.js
  form-signup.js
  index.html
  items.html
  login.html
  login_signup.css
  reset_1.css
  signup.html
  style.css
Labels: 매운맛🔥, 진행 중 🏃, 최종 제출

#39 [정부광] Sprint-mission4
  sprint-mission-4/Article.js
  sprint-mission-4/Product.js
  sprint-mission-4/README.md
  sprint-mission-4/index.html
  sprint-mission-4/main.js
Labels: 매운맛🔥, 미완성🫠, 최종 제출

#42 [김태홍] sprint4
  README.md
  article.js
  index.html
  login/image/close_eye.png
  login/image/open_eye.png
  login/login.html
  login/login.js
  login/signup.html
  login/signup.js
  login/styleSheet/login.css
  login/styleSheet/signup.css
  main.js
  package.json
  product.js
Labels: 매운맛🔥, 미완성🫠, 최종 제출

#38 이유진 - 스프린트 미션4
  js/api/ArticleService.js
  js/api/ProductService.js
  js/main.js
  package.json
Labels: 매운맛🔥

#41 Basic 오해상 sprint4
  ArticleService.js
  ProductService.js
  form-login.js
  form-signup.js
  index.html
  main.js
Labels: 매운맛🔥, 진행 중 🏃, 최종 제출

#48 [정우진] sprint4
  articleService.js
  login.html
  login.js
  main.js
  productService.js
  signup.html
  signup.js
  userList.js
Labels: 매운맛🔥, 제출일 이후 제출한PR, 최종 제출
